id = "org.standardnotes.mfa-link"
npm = "sn-mfa-link"
github = "sn-extensions/mfa-link"
main = "index.html"

name = "2FA Manager"
area = "modal"
content_type = "SN|Component"
version = "1.2.1"
description = "Configure two-factor authentication to add an extra level of security to your account."
flags = []
